name: Open Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: fateyan/action-discord-notifier@v1
        with:
          message-title: New PR Created [{{ EVENT_PAYLOAD.pull_request.number }}]({{ EVENT_PAYLOAD.pull_request.html_url }})
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
