name: Open Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord close notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'New PR [#{{ EVENT_PAYLOAD.pull_request.number }}]({{ EVENT_PAYLOAD.pull_request.html_url }})'
